targets:
  $default:
    builders:
      drift_dev:
        options:
          override_hash_and_equals_in_result_sets: true
          apply_converters_on_variables: true
          store_date_time_values_as_text: true
          mutable_classes: true
          named_parameters: true
          sql:
            dialect: sqlite
            options:
              version: "3.38"
              modules:
                - json1
                - fts5
                # - math