name: client
description: "PocketBase FLutter Client"
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pocketbase: ^0.18.1
  http: ^1.2.1
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.23
  path_provider: ^2.1.3
  path: ^1.9.0
  collection: ^1.18.0
  dart_mappable: ^4.2.2
  intl: ^0.19.0
  signals: ^5.2.2
  go_router: ^14.2.0
  form_builder_validators: ^10.0.1
  timeago: ^3.6.1
  sqlite3: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.11
  dart_mappable_builder: ^4.2.3

flutter:
  uses-material-design: true
